### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by willcode4tacos** [angela-andrews/upenn-project1#9] opened 2018-06-26 13:49 UTC
Weighted averages are used to determine the voting results based on first and second choices.
The final result shows the top pick/ top 3 picks(BL)

**Comment by CatLibWilk** [comment] 2018-06-26 14:08
oops, didn't realize that in making issue #10 I was duplicating this issue.  Should we delete one of them?

**Comment by CatLibWilk** [comment] 2018-06-28 18:20
closed as duplicate of 10 and 8

**Closed** 2018-06-28 18:20 UTC
